DROP TABLE IF EXISTS filial;
CREATE TABLE IF NOT EXISTS filial(
    id INT AUTO_INCREMENT UNSIGNED PRIMARY KEY,
    nome VARCHAR(300) NOT NULL,
    rua VARCHAR(10) NOT NULL,
    numero VARCHAR(5) NOT NULL,
    cidade VARCHAR(300) NOT NULL,
    estado VARCHAR(300) NOT NULL
    cincoEstrelas BIT;
);